sudo: true
cache:
  directories:
  - $HOME/.gradle/caches/
language: groovy
jdk:
  - oraclejdk8
  - openjdk7
before_install:
  - chmod +x .travis/before_install.sh
  - .travis/before_install.sh

